name: Trigger QA Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Playwright tests repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}  // Personal Access Token with repo permissions
          repository: Musmanghani211/Login-page-CiCdTesting-playwright
          event-type: run-playwright-tests