name: Trigger QA Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  trigger-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger QA workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Musmanghani211/Login-page-CiCdTesting-playwright
          event-type: run-playwright-tests